### ISSUE TITLE
UTF-8 vs. CP-1253

### ISSUE THREAD

**Issue by bandrel** [ZephrFish/PotFileUtils#1]
converting from hex to UTF-8 you'll run into a bunch of issues. Recommend changing to CP-1253 if you run into issues

**Comment by ZephrFish** [comment]
Thanks I'll amend and update

**Comment by bandrel** [comment]
https://github.com/ZephrFish/PotFileUtils/blob/655372e0a8e727a9c09ac53d8a601122b54aeb6c/PotUtils.py#L79C78-L79C78

**Comment by ZephrFish** [comment]
Tested and updated thanks!
